// Mocks generated by Mockito from annotations
// in smara_accounting/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:io' as _i36;
import 'dart:ui' as _i50;

import 'package:flutter/services.dart' as _i51;
import 'package:flutter/widgets.dart' as _i52;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:smara_accounting/data/database/app_database.dart' as _i19;
import 'package:smara_accounting/data/database/tables/account_groups_table.dart'
    as _i27;
import 'package:smara_accounting/data/database/tables/accounts_table.dart'
    as _i26;
import 'package:smara_accounting/data/database/tables/ofx_import_records_table.dart'
    as _i45;
import 'package:smara_accounting/data/exchange_rate_service.dart' as _i37;
import 'package:smara_accounting/data/repositories/account_repository.dart'
    as _i24;
import 'package:smara_accounting/data/repositories/category_repository.dart'
    as _i28;
import 'package:smara_accounting/data/repositories/identity_repository.dart'
    as _i7;
import 'package:smara_accounting/data/repositories/investment_holdings_logic.dart'
    as _i33;
import 'package:smara_accounting/data/repositories/investment_repository.dart'
    as _i30;
import 'package:smara_accounting/data/repositories/ledger_backup_repository.dart'
    as _i35;
import 'package:smara_accounting/data/repositories/ledger_repository.dart'
    as _i14;
import 'package:smara_accounting/data/repositories/payee_repository.dart'
    as _i29;
import 'package:smara_accounting/data/repositories/recurring_template_repository.dart'
    as _i34;
import 'package:smara_accounting/data/repositories/settings_repository.dart'
    as _i39;
import 'package:smara_accounting/data/repositories/statement_import_repository.dart'
    as _i42;
import 'package:smara_accounting/domain/crypto/signing_key_service.dart' as _i5;
import 'package:smara_accounting/domain/csv/csv_column_mapping.dart' as _i43;
import 'package:smara_accounting/domain/csv/csv_import_profile.dart' as _i46;
import 'package:smara_accounting/domain/lock/app_lock_policy.dart' as _i13;
import 'package:smara_accounting/domain/lock/app_lock_service.dart' as _i47;
import 'package:smara_accounting/domain/lock/biometric_authenticator.dart'
    as _i48;
import 'package:smara_accounting/domain/models/account.dart' as _i2;
import 'package:smara_accounting/domain/models/account_currency_catalog.dart'
    as _i25;
import 'package:smara_accounting/domain/models/account_group.dart' as _i3;
import 'package:smara_accounting/domain/models/exchange_rate_provider.dart'
    as _i38;
import 'package:smara_accounting/domain/models/home_overview.dart' as _i21;
import 'package:smara_accounting/domain/models/instrument.dart' as _i8;
import 'package:smara_accounting/domain/models/instrument_holding.dart' as _i31;
import 'package:smara_accounting/domain/models/instrument_quote.dart' as _i32;
import 'package:smara_accounting/domain/models/integrity_event.dart' as _i23;
import 'package:smara_accounting/domain/models/journal_entry.dart' as _i16;
import 'package:smara_accounting/domain/models/payee.dart' as _i4;
import 'package:smara_accounting/domain/models/pending_transfer.dart' as _i20;
import 'package:smara_accounting/domain/models/quote_provider.dart' as _i40;
import 'package:smara_accounting/domain/models/recurring_template.dart' as _i9;
import 'package:smara_accounting/domain/models/research_tool.dart' as _i41;
import 'package:smara_accounting/domain/models/signing_identity.dart' as _i6;
import 'package:smara_accounting/domain/models/summary.dart' as _i22;
import 'package:smara_accounting/domain/models/transaction_direction.dart'
    as _i17;
import 'package:smara_accounting/domain/statement_import/category_rule.dart'
    as _i44;
import 'package:smara_accounting/domain/statement_import/parsed_statement_transaction.dart'
    as _i10;
import 'package:smara_accounting/domain/statement_import/statement_import_batch.dart'
    as _i12;
import 'package:smara_accounting/domain/statement_import/statement_import_preview.dart'
    as _i11;
import 'package:smara_accounting/ui/core/app_lock_controller.dart' as _i49;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccount_0 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountGroup_1 extends _i1.SmartFake implements _i3.AccountGroup {
  _FakeAccountGroup_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayee_2 extends _i1.SmartFake implements _i4.Payee {
  _FakePayee_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedIdentity_3 extends _i1.SmartFake
    implements _i5.GeneratedIdentity {
  _FakeGeneratedIdentity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSigningIdentity_4 extends _i1.SmartFake
    implements _i6.SigningIdentity {
  _FakeSigningIdentity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChainVerificationResult_5 extends _i1.SmartFake
    implements _i7.ChainVerificationResult {
  _FakeChainVerificationResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInstrument_6 extends _i1.SmartFake implements _i8.Instrument {
  _FakeInstrument_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecurringTemplate_7 extends _i1.SmartFake
    implements _i9.RecurringTemplate {
  _FakeRecurringTemplate_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatementParseResult_8 extends _i1.SmartFake
    implements _i10.StatementParseResult {
  _FakeStatementParseResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatementImportPreview_9 extends _i1.SmartFake
    implements _i11.StatementImportPreview {
  _FakeStatementImportPreview_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatementImportBatchResult_10 extends _i1.SmartFake
    implements _i12.StatementImportBatchResult {
  _FakeStatementImportBatchResult_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppLockPolicy_11 extends _i1.SmartFake
    implements _i13.AppLockPolicy {
  _FakeAppLockPolicy_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LedgerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLedgerRepository extends _i1.Mock implements _i14.LedgerRepository {
  @override
  _i15.Future<bool> hasAnyJournalEntries() =>
      (super.noSuchMethod(
            Invocation.method(#hasAnyJournalEntries, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<List<_i16.JournalEntry>> watchEntries() =>
      (super.noSuchMethod(
            Invocation.method(#watchEntries, []),
            returnValue: _i15.Stream<List<_i16.JournalEntry>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i16.JournalEntry>>.empty(),
          )
          as _i15.Stream<List<_i16.JournalEntry>>);

  @override
  _i15.Future<String> recordTransaction({
    required int? amountMinor,
    required _i17.TransactionDirection? direction,
    required String? categoryId,
    required String? financialAccountId,
    required DateTime? transactionDate,
    String? description,
    String? nativeCurrency,
    int? accountCurrencyAmountMinor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordTransaction, [], {
              #amountMinor: amountMinor,
              #direction: direction,
              #categoryId: categoryId,
              #financialAccountId: financialAccountId,
              #transactionDate: transactionDate,
              #description: description,
              #nativeCurrency: nativeCurrency,
              #accountCurrencyAmountMinor: accountCurrencyAmountMinor,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordTransaction, [], {
                  #amountMinor: amountMinor,
                  #direction: direction,
                  #categoryId: categoryId,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                  #nativeCurrency: nativeCurrency,
                  #accountCurrencyAmountMinor: accountCurrencyAmountMinor,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordTransaction, [], {
                  #amountMinor: amountMinor,
                  #direction: direction,
                  #categoryId: categoryId,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                  #nativeCurrency: nativeCurrency,
                  #accountCurrencyAmountMinor: accountCurrencyAmountMinor,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<String> recordSplitTransaction({
    required int? totalAmountMinor,
    required List<({int amountMinor, String categoryId})>? splitLines,
    required _i17.TransactionDirection? direction,
    required String? financialAccountId,
    required DateTime? transactionDate,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordSplitTransaction, [], {
              #totalAmountMinor: totalAmountMinor,
              #splitLines: splitLines,
              #direction: direction,
              #financialAccountId: financialAccountId,
              #transactionDate: transactionDate,
              #description: description,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordSplitTransaction, [], {
                  #totalAmountMinor: totalAmountMinor,
                  #splitLines: splitLines,
                  #direction: direction,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordSplitTransaction, [], {
                  #totalAmountMinor: totalAmountMinor,
                  #splitLines: splitLines,
                  #direction: direction,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<void> recordTransfer({
    required String? fromAccountId,
    required String? toAccountId,
    required int? amountMinor,
    required DateTime? transactionDate,
    String? description,
    int? destinationAmountMinor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordTransfer, [], {
              #fromAccountId: fromAccountId,
              #toAccountId: toAccountId,
              #amountMinor: amountMinor,
              #transactionDate: transactionDate,
              #description: description,
              #destinationAmountMinor: destinationAmountMinor,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> postTransferEntry({
    required _i19.AccountRow? fromAccount,
    required _i19.AccountRow? toAccount,
    required int? amountMinor,
    required DateTime? transactionDate,
    String? description,
    int? destinationAmountMinor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postTransferEntry, [], {
              #fromAccount: fromAccount,
              #toAccount: toAccount,
              #amountMinor: amountMinor,
              #transactionDate: transactionDate,
              #description: description,
              #destinationAmountMinor: destinationAmountMinor,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> reverseEntry(String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#reverseEntry, [entryId]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> fixPostedTransaction({
    required String? entryId,
    required int? amountMinor,
    required _i17.TransactionDirection? direction,
    required String? categoryId,
    required String? financialAccountId,
    required DateTime? transactionDate,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fixPostedTransaction, [], {
              #entryId: entryId,
              #amountMinor: amountMinor,
              #direction: direction,
              #categoryId: categoryId,
              #financialAccountId: financialAccountId,
              #transactionDate: transactionDate,
              #description: description,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#fixPostedTransaction, [], {
                  #entryId: entryId,
                  #amountMinor: amountMinor,
                  #direction: direction,
                  #categoryId: categoryId,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#fixPostedTransaction, [], {
                  #entryId: entryId,
                  #amountMinor: amountMinor,
                  #direction: direction,
                  #categoryId: categoryId,
                  #financialAccountId: financialAccountId,
                  #transactionDate: transactionDate,
                  #description: description,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Stream<List<_i20.PendingTransfer>> watchPendingTransfers() =>
      (super.noSuchMethod(
            Invocation.method(#watchPendingTransfers, []),
            returnValue: _i15.Stream<List<_i20.PendingTransfer>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i20.PendingTransfer>>.empty(),
          )
          as _i15.Stream<List<_i20.PendingTransfer>>);

  @override
  _i15.Future<void> settlePendingTransfer({
    required String? pendingTransferId,
    required String? settledToAccountId,
    required int? settledAmountMinor,
    String? feeCategoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#settlePendingTransfer, [], {
              #pendingTransferId: pendingTransferId,
              #settledToAccountId: settledToAccountId,
              #settledAmountMinor: settledAmountMinor,
              #feeCategoryId: feeCategoryId,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> appendSignedEntry({
    required String? transactionDate,
    String? description,
    String? reversesEntryId,
    required List<({String accountId, int amountMinor, int lineNumber})>?
    postings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appendSignedEntry, [], {
              #transactionDate: transactionDate,
              #description: description,
              #reversesEntryId: reversesEntryId,
              #postings: postings,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#appendSignedEntry, [], {
                  #transactionDate: transactionDate,
                  #description: description,
                  #reversesEntryId: reversesEntryId,
                  #postings: postings,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#appendSignedEntry, [], {
                  #transactionDate: transactionDate,
                  #description: description,
                  #reversesEntryId: reversesEntryId,
                  #postings: postings,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Stream<List<_i16.JournalEntry>> watchEntriesForAccount(
    String? financialAccountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchEntriesForAccount, [financialAccountId]),
            returnValue: _i15.Stream<List<_i16.JournalEntry>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i16.JournalEntry>>.empty(),
          )
          as _i15.Stream<List<_i16.JournalEntry>>);

  @override
  _i15.Future<int> displayBalanceMinor(String? financialAccountId) =>
      (super.noSuchMethod(
            Invocation.method(#displayBalanceMinor, [financialAccountId]),
            returnValue: _i15.Future<int>.value(0),
            returnValueForMissingStub: _i15.Future<int>.value(0),
          )
          as _i15.Future<int>);

  @override
  _i15.Future<String> exportLedgerCsv({
    required String? financialAccountId,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportLedgerCsv, [], {
              #financialAccountId: financialAccountId,
              #start: start,
              #end: end,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportLedgerCsv, [], {
                  #financialAccountId: financialAccountId,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportLedgerCsv, [], {
                  #financialAccountId: financialAccountId,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Stream<_i21.HomeOverview> watchHomeOverview() =>
      (super.noSuchMethod(
            Invocation.method(#watchHomeOverview, []),
            returnValue: _i15.Stream<_i21.HomeOverview>.empty(),
            returnValueForMissingStub: _i15.Stream<_i21.HomeOverview>.empty(),
          )
          as _i15.Stream<_i21.HomeOverview>);

  @override
  _i15.Stream<_i22.LedgerSummary> watchSummary({
    required DateTime? start,
    required DateTime? end,
    String? financialAccountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchSummary, [], {
              #start: start,
              #end: end,
              #financialAccountId: financialAccountId,
            }),
            returnValue: _i15.Stream<_i22.LedgerSummary>.empty(),
            returnValueForMissingStub: _i15.Stream<_i22.LedgerSummary>.empty(),
          )
          as _i15.Stream<_i22.LedgerSummary>);

  @override
  _i15.Stream<List<_i23.IntegrityEvent>> watchIntegrityEvents() =>
      (super.noSuchMethod(
            Invocation.method(#watchIntegrityEvents, []),
            returnValue: _i15.Stream<List<_i23.IntegrityEvent>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i23.IntegrityEvent>>.empty(),
          )
          as _i15.Stream<List<_i23.IntegrityEvent>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i24.AccountRepository {
  @override
  _i15.Future<bool> needsCurrencyBackfill() =>
      (super.noSuchMethod(
            Invocation.method(#needsCurrencyBackfill, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> backfillGroupCurrencies(String? currency) =>
      (super.noSuchMethod(
            Invocation.method(#backfillGroupCurrencies, [currency]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<List<_i2.Account>> watchFinancialAccounts({
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchFinancialAccounts, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i15.Stream<List<_i2.Account>>.empty(),
            returnValueForMissingStub: _i15.Stream<List<_i2.Account>>.empty(),
          )
          as _i15.Stream<List<_i2.Account>>);

  @override
  _i15.Stream<List<_i3.AccountGroup>> watchAccountGroups({
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountGroups, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i15.Stream<List<_i3.AccountGroup>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i3.AccountGroup>>.empty(),
          )
          as _i15.Stream<List<_i3.AccountGroup>>);

  @override
  _i15.Stream<_i25.AccountCurrencyCatalog> watchAccountCurrencies({
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountCurrencies, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i15.Stream<_i25.AccountCurrencyCatalog>.empty(),
            returnValueForMissingStub:
                _i15.Stream<_i25.AccountCurrencyCatalog>.empty(),
          )
          as _i15.Stream<_i25.AccountCurrencyCatalog>);

  @override
  _i15.Future<String?> groupCurrencyFor(String? financialAccountId) =>
      (super.noSuchMethod(
            Invocation.method(#groupCurrencyFor, [financialAccountId]),
            returnValue: _i15.Future<String?>.value(),
            returnValueForMissingStub: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<_i2.Account> createFinancialAccount({
    required String? name,
    required _i26.AccountType? type,
    required String? groupId,
    int? openingBalanceMinor,
    bool? holdsInvestments = false,
    bool? isCreditCard = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFinancialAccount, [], {
              #name: name,
              #type: type,
              #groupId: groupId,
              #openingBalanceMinor: openingBalanceMinor,
              #holdsInvestments: holdsInvestments,
              #isCreditCard: isCreditCard,
            }),
            returnValue: _i15.Future<_i2.Account>.value(
              _FakeAccount_0(
                this,
                Invocation.method(#createFinancialAccount, [], {
                  #name: name,
                  #type: type,
                  #groupId: groupId,
                  #openingBalanceMinor: openingBalanceMinor,
                  #holdsInvestments: holdsInvestments,
                  #isCreditCard: isCreditCard,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i2.Account>.value(
              _FakeAccount_0(
                this,
                Invocation.method(#createFinancialAccount, [], {
                  #name: name,
                  #type: type,
                  #groupId: groupId,
                  #openingBalanceMinor: openingBalanceMinor,
                  #holdsInvestments: holdsInvestments,
                  #isCreditCard: isCreditCard,
                }),
              ),
            ),
          )
          as _i15.Future<_i2.Account>);

  @override
  _i15.Future<void> renameFinancialAccount({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameFinancialAccount, [], {
              #id: id,
              #newName: newName,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> reassignFinancialAccountGroup({
    required String? id,
    required String? groupId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reassignFinancialAccountGroup, [], {
              #id: id,
              #groupId: groupId,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> changeAccountGroupCurrency({
    required String? groupId,
    required String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeAccountGroupCurrency, [], {
              #groupId: groupId,
              #currency: currency,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> archiveFinancialAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveFinancialAccount, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> unarchiveFinancialAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveFinancialAccount, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> renameAccountGroup({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameAccountGroup, [], {
              #id: id,
              #newName: newName,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i3.AccountGroup> createAccountGroup({
    required String? name,
    required _i27.AccountGroupKind? kind,
    required String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccountGroup, [], {
              #name: name,
              #kind: kind,
              #currency: currency,
            }),
            returnValue: _i15.Future<_i3.AccountGroup>.value(
              _FakeAccountGroup_1(
                this,
                Invocation.method(#createAccountGroup, [], {
                  #name: name,
                  #kind: kind,
                  #currency: currency,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i3.AccountGroup>.value(
              _FakeAccountGroup_1(
                this,
                Invocation.method(#createAccountGroup, [], {
                  #name: name,
                  #kind: kind,
                  #currency: currency,
                }),
              ),
            ),
          )
          as _i15.Future<_i3.AccountGroup>);

  @override
  _i15.Future<void> archiveAccountGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveAccountGroup, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> unarchiveAccountGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveAccountGroup, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> deleteAccountGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccountGroup, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> recordArchivedAccountCloseoutTransfer({
    required String? fromAccountId,
    required String? toAccountId,
    required DateTime? transactionDate,
    String? description,
    int? destinationAmountMinor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordArchivedAccountCloseoutTransfer, [], {
              #fromAccountId: fromAccountId,
              #toAccountId: toAccountId,
              #transactionDate: transactionDate,
              #description: description,
              #destinationAmountMinor: destinationAmountMinor,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> seedOnboardingBooks({required String? currency}) =>
      (super.noSuchMethod(
            Invocation.method(#seedOnboardingBooks, [], {#currency: currency}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i28.CategoryRepository {
  @override
  _i15.Stream<List<_i2.Account>> watchCategories({
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCategories, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i15.Stream<List<_i2.Account>>.empty(),
            returnValueForMissingStub: _i15.Stream<List<_i2.Account>>.empty(),
          )
          as _i15.Stream<List<_i2.Account>>);

  @override
  _i15.Future<void> addCategory({
    required String? name,
    required _i26.AccountType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [], {#name: name, #type: type}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> renameCategory({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameCategory, [], {
              #id: id,
              #newName: newName,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> archiveCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveCategory, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> unarchiveCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveCategory, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setCategoryMonthlyLimit({
    required String? id,
    required int? monthlyLimitMinor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setCategoryMonthlyLimit, [], {
              #id: id,
              #monthlyLimitMinor: monthlyLimitMinor,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<List<_i22.CategoryTotal>> watchCategoryTotals({
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoryTotals, [], {
              #start: start,
              #end: end,
            }),
            returnValue: _i15.Stream<List<_i22.CategoryTotal>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i22.CategoryTotal>>.empty(),
          )
          as _i15.Stream<List<_i22.CategoryTotal>>);
}

/// A class which mocks [PayeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayeeRepository extends _i1.Mock implements _i29.PayeeRepository {
  @override
  _i15.Stream<List<_i4.Payee>> watchPayees() =>
      (super.noSuchMethod(
            Invocation.method(#watchPayees, []),
            returnValue: _i15.Stream<List<_i4.Payee>>.empty(),
            returnValueForMissingStub: _i15.Stream<List<_i4.Payee>>.empty(),
          )
          as _i15.Stream<List<_i4.Payee>>);

  @override
  _i15.Future<_i4.Payee> createPayee({
    required String? name,
    String? defaultCategoryId,
    String? defaultFinancialAccountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPayee, [], {
              #name: name,
              #defaultCategoryId: defaultCategoryId,
              #defaultFinancialAccountId: defaultFinancialAccountId,
            }),
            returnValue: _i15.Future<_i4.Payee>.value(
              _FakePayee_2(
                this,
                Invocation.method(#createPayee, [], {
                  #name: name,
                  #defaultCategoryId: defaultCategoryId,
                  #defaultFinancialAccountId: defaultFinancialAccountId,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i4.Payee>.value(
              _FakePayee_2(
                this,
                Invocation.method(#createPayee, [], {
                  #name: name,
                  #defaultCategoryId: defaultCategoryId,
                  #defaultFinancialAccountId: defaultFinancialAccountId,
                }),
              ),
            ),
          )
          as _i15.Future<_i4.Payee>);

  @override
  _i15.Future<_i4.Payee> findOrCreatePayeeByName({
    required String? name,
    String? defaultCategoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreatePayeeByName, [], {
              #name: name,
              #defaultCategoryId: defaultCategoryId,
            }),
            returnValue: _i15.Future<_i4.Payee>.value(
              _FakePayee_2(
                this,
                Invocation.method(#findOrCreatePayeeByName, [], {
                  #name: name,
                  #defaultCategoryId: defaultCategoryId,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i4.Payee>.value(
              _FakePayee_2(
                this,
                Invocation.method(#findOrCreatePayeeByName, [], {
                  #name: name,
                  #defaultCategoryId: defaultCategoryId,
                }),
              ),
            ),
          )
          as _i15.Future<_i4.Payee>);

  @override
  _i15.Future<void> renamePayee({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renamePayee, [], {#id: id, #newName: newName}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> deletePayee(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayee, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> recordPayeeUsage({
    required String? payeeId,
    required String? categoryId,
    required String? financialAccountId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPayeeUsage, [], {
              #payeeId: payeeId,
              #categoryId: categoryId,
              #financialAccountId: financialAccountId,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [IdentityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityRepository extends _i1.Mock
    implements _i7.IdentityRepository {
  @override
  _i15.Future<_i6.SigningIdentity?> currentIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#currentIdentity, []),
            returnValue: _i15.Future<_i6.SigningIdentity?>.value(),
            returnValueForMissingStub:
                _i15.Future<_i6.SigningIdentity?>.value(),
          )
          as _i15.Future<_i6.SigningIdentity?>);

  @override
  _i15.Future<bool> hasMatchingStoredKey(_i6.SigningIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#hasMatchingStoredKey, [identity]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<_i5.GeneratedIdentity> generateFirstIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#generateFirstIdentity, []),
            returnValue: _i15.Future<_i5.GeneratedIdentity>.value(
              _FakeGeneratedIdentity_3(
                this,
                Invocation.method(#generateFirstIdentity, []),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i5.GeneratedIdentity>.value(
              _FakeGeneratedIdentity_3(
                this,
                Invocation.method(#generateFirstIdentity, []),
              ),
            ),
          )
          as _i15.Future<_i5.GeneratedIdentity>);

  @override
  _i15.Future<void> stashPendingPhraseWords(List<String>? words) =>
      (super.noSuchMethod(
            Invocation.method(#stashPendingPhraseWords, [words]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i5.GeneratedIdentity?> resumePendingIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#resumePendingIdentity, []),
            returnValue: _i15.Future<_i5.GeneratedIdentity?>.value(),
            returnValueForMissingStub:
                _i15.Future<_i5.GeneratedIdentity?>.value(),
          )
          as _i15.Future<_i5.GeneratedIdentity?>);

  @override
  _i15.Future<_i6.SigningIdentity> confirmFirstIdentity(
    _i5.GeneratedIdentity? generated, {
    required String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmFirstIdentity,
              [generated],
              {#currency: currency},
            ),
            returnValue: _i15.Future<_i6.SigningIdentity>.value(
              _FakeSigningIdentity_4(
                this,
                Invocation.method(
                  #confirmFirstIdentity,
                  [generated],
                  {#currency: currency},
                ),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i6.SigningIdentity>.value(
              _FakeSigningIdentity_4(
                this,
                Invocation.method(
                  #confirmFirstIdentity,
                  [generated],
                  {#currency: currency},
                ),
              ),
            ),
          )
          as _i15.Future<_i6.SigningIdentity>);

  @override
  _i15.Future<_i6.SigningIdentity> restoreIdentity({
    List<String>? recoveryPhraseWords,
    String? keystoreFileContents,
    String? keystorePassphrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreIdentity, [], {
              #recoveryPhraseWords: recoveryPhraseWords,
              #keystoreFileContents: keystoreFileContents,
              #keystorePassphrase: keystorePassphrase,
            }),
            returnValue: _i15.Future<_i6.SigningIdentity>.value(
              _FakeSigningIdentity_4(
                this,
                Invocation.method(#restoreIdentity, [], {
                  #recoveryPhraseWords: recoveryPhraseWords,
                  #keystoreFileContents: keystoreFileContents,
                  #keystorePassphrase: keystorePassphrase,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i6.SigningIdentity>.value(
              _FakeSigningIdentity_4(
                this,
                Invocation.method(#restoreIdentity, [], {
                  #recoveryPhraseWords: recoveryPhraseWords,
                  #keystoreFileContents: keystoreFileContents,
                  #keystorePassphrase: keystorePassphrase,
                }),
              ),
            ),
          )
          as _i15.Future<_i6.SigningIdentity>);

  @override
  _i15.Future<_i5.GeneratedIdentity> migrateToNewIdentityAfterKeyLoss() =>
      (super.noSuchMethod(
            Invocation.method(#migrateToNewIdentityAfterKeyLoss, []),
            returnValue: _i15.Future<_i5.GeneratedIdentity>.value(
              _FakeGeneratedIdentity_3(
                this,
                Invocation.method(#migrateToNewIdentityAfterKeyLoss, []),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i5.GeneratedIdentity>.value(
              _FakeGeneratedIdentity_3(
                this,
                Invocation.method(#migrateToNewIdentityAfterKeyLoss, []),
              ),
            ),
          )
          as _i15.Future<_i5.GeneratedIdentity>);

  @override
  _i15.Future<void> acknowledgeIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeIdentity, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i7.ChainVerificationResult> verifyChain() =>
      (super.noSuchMethod(
            Invocation.method(#verifyChain, []),
            returnValue: _i15.Future<_i7.ChainVerificationResult>.value(
              _FakeChainVerificationResult_5(
                this,
                Invocation.method(#verifyChain, []),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i7.ChainVerificationResult>.value(
                  _FakeChainVerificationResult_5(
                    this,
                    Invocation.method(#verifyChain, []),
                  ),
                ),
          )
          as _i15.Future<_i7.ChainVerificationResult>);

  @override
  _i15.Future<String> exportKeystoreFile({required String? passphrase}) =>
      (super.noSuchMethod(
            Invocation.method(#exportKeystoreFile, [], {
              #passphrase: passphrase,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportKeystoreFile, [], {
                  #passphrase: passphrase,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportKeystoreFile, [], {
                  #passphrase: passphrase,
                }),
              ),
            ),
          )
          as _i15.Future<String>);
}

/// A class which mocks [InvestmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvestmentRepository extends _i1.Mock
    implements _i30.InvestmentRepository {
  @override
  _i15.Stream<List<_i8.Instrument>> watchInstruments({
    bool? includeArchived = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchInstruments, [], {
              #includeArchived: includeArchived,
            }),
            returnValue: _i15.Stream<List<_i8.Instrument>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i8.Instrument>>.empty(),
          )
          as _i15.Stream<List<_i8.Instrument>>);

  @override
  _i15.Future<_i8.Instrument> createInstrument({
    required String? name,
    required _i8.InstrumentKind? kind,
    String? ticker,
    String? isin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInstrument, [], {
              #name: name,
              #kind: kind,
              #ticker: ticker,
              #isin: isin,
            }),
            returnValue: _i15.Future<_i8.Instrument>.value(
              _FakeInstrument_6(
                this,
                Invocation.method(#createInstrument, [], {
                  #name: name,
                  #kind: kind,
                  #ticker: ticker,
                  #isin: isin,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i8.Instrument>.value(
              _FakeInstrument_6(
                this,
                Invocation.method(#createInstrument, [], {
                  #name: name,
                  #kind: kind,
                  #ticker: ticker,
                  #isin: isin,
                }),
              ),
            ),
          )
          as _i15.Future<_i8.Instrument>);

  @override
  _i15.Future<void> renameInstrument({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameInstrument, [], {
              #id: id,
              #newName: newName,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> archiveInstrument(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveInstrument, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<List<_i31.InstrumentHolding>> watchHoldingsForAccount(
    String? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchHoldingsForAccount, [accountId]),
            returnValue: _i15.Stream<List<_i31.InstrumentHolding>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i31.InstrumentHolding>>.empty(),
          )
          as _i15.Stream<List<_i31.InstrumentHolding>>);

  @override
  _i15.Stream<List<_i8.Instrument>> watchInstrumentsHeldInAccount(
    String? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchInstrumentsHeldInAccount, [accountId]),
            returnValue: _i15.Stream<List<_i8.Instrument>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i8.Instrument>>.empty(),
          )
          as _i15.Stream<List<_i8.Instrument>>);

  @override
  _i15.Future<List<_i8.Instrument>> computeInstrumentsHeldInAccount(
    String? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#computeInstrumentsHeldInAccount, [accountId]),
            returnValue: _i15.Future<List<_i8.Instrument>>.value(
              <_i8.Instrument>[],
            ),
            returnValueForMissingStub: _i15.Future<List<_i8.Instrument>>.value(
              <_i8.Instrument>[],
            ),
          )
          as _i15.Future<List<_i8.Instrument>>);

  @override
  _i15.Stream<List<_i32.InstrumentQuote>> watchInstrumentQuotes() =>
      (super.noSuchMethod(
            Invocation.method(#watchInstrumentQuotes, []),
            returnValue: _i15.Stream<List<_i32.InstrumentQuote>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i32.InstrumentQuote>>.empty(),
          )
          as _i15.Stream<List<_i32.InstrumentQuote>>);

  @override
  _i15.Future<void> cacheInstrumentQuote({
    required String? instrumentId,
    required int? priceMinor,
    required String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheInstrumentQuote, [], {
              #instrumentId: instrumentId,
              #priceMinor: priceMinor,
              #currency: currency,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> recordBuy({
    required String? accountId,
    required String? instrumentId,
    required int? quantityScaled,
    required int? unitPriceMinor,
    required DateTime? transactionDate,
    required _i33.BuyFundingSource? fundingSource,
    String? incomeCategoryId,
    DateTime? lockedUntil,
    String? description,
    int? brokerageMinor,
    String? brokerageExpenseCategoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordBuy, [], {
              #accountId: accountId,
              #instrumentId: instrumentId,
              #quantityScaled: quantityScaled,
              #unitPriceMinor: unitPriceMinor,
              #transactionDate: transactionDate,
              #fundingSource: fundingSource,
              #incomeCategoryId: incomeCategoryId,
              #lockedUntil: lockedUntil,
              #description: description,
              #brokerageMinor: brokerageMinor,
              #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordBuy, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #quantityScaled: quantityScaled,
                  #unitPriceMinor: unitPriceMinor,
                  #transactionDate: transactionDate,
                  #fundingSource: fundingSource,
                  #incomeCategoryId: incomeCategoryId,
                  #lockedUntil: lockedUntil,
                  #description: description,
                  #brokerageMinor: brokerageMinor,
                  #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordBuy, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #quantityScaled: quantityScaled,
                  #unitPriceMinor: unitPriceMinor,
                  #transactionDate: transactionDate,
                  #fundingSource: fundingSource,
                  #incomeCategoryId: incomeCategoryId,
                  #lockedUntil: lockedUntil,
                  #description: description,
                  #brokerageMinor: brokerageMinor,
                  #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<String> recordSell({
    required String? accountId,
    required String? instrumentId,
    required int? quantityScaled,
    required int? unitPriceMinor,
    required DateTime? transactionDate,
    String? gainIncomeCategoryId,
    String? lossExpenseCategoryId,
    String? description,
    int? brokerageMinor,
    String? brokerageExpenseCategoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordSell, [], {
              #accountId: accountId,
              #instrumentId: instrumentId,
              #quantityScaled: quantityScaled,
              #unitPriceMinor: unitPriceMinor,
              #transactionDate: transactionDate,
              #gainIncomeCategoryId: gainIncomeCategoryId,
              #lossExpenseCategoryId: lossExpenseCategoryId,
              #description: description,
              #brokerageMinor: brokerageMinor,
              #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordSell, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #quantityScaled: quantityScaled,
                  #unitPriceMinor: unitPriceMinor,
                  #transactionDate: transactionDate,
                  #gainIncomeCategoryId: gainIncomeCategoryId,
                  #lossExpenseCategoryId: lossExpenseCategoryId,
                  #description: description,
                  #brokerageMinor: brokerageMinor,
                  #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordSell, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #quantityScaled: quantityScaled,
                  #unitPriceMinor: unitPriceMinor,
                  #transactionDate: transactionDate,
                  #gainIncomeCategoryId: gainIncomeCategoryId,
                  #lossExpenseCategoryId: lossExpenseCategoryId,
                  #description: description,
                  #brokerageMinor: brokerageMinor,
                  #brokerageExpenseCategoryId: brokerageExpenseCategoryId,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<String> recordDividend({
    required String? accountId,
    required String? instrumentId,
    required int? amountMinor,
    required DateTime? transactionDate,
    required String? incomeCategoryId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordDividend, [], {
              #accountId: accountId,
              #instrumentId: instrumentId,
              #amountMinor: amountMinor,
              #transactionDate: transactionDate,
              #incomeCategoryId: incomeCategoryId,
              #description: description,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordDividend, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #amountMinor: amountMinor,
                  #transactionDate: transactionDate,
                  #incomeCategoryId: incomeCategoryId,
                  #description: description,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordDividend, [], {
                  #accountId: accountId,
                  #instrumentId: instrumentId,
                  #amountMinor: amountMinor,
                  #transactionDate: transactionDate,
                  #incomeCategoryId: incomeCategoryId,
                  #description: description,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<List<_i31.InstrumentHolding>> computeHoldingsForAccount(
    String? accountId, {
    bool? includeZeroQuantity = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #computeHoldingsForAccount,
              [accountId],
              {#includeZeroQuantity: includeZeroQuantity},
            ),
            returnValue: _i15.Future<List<_i31.InstrumentHolding>>.value(
              <_i31.InstrumentHolding>[],
            ),
            returnValueForMissingStub:
                _i15.Future<List<_i31.InstrumentHolding>>.value(
                  <_i31.InstrumentHolding>[],
                ),
          )
          as _i15.Future<List<_i31.InstrumentHolding>>);
}

/// A class which mocks [RecurringTemplateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecurringTemplateRepository extends _i1.Mock
    implements _i34.RecurringTemplateRepository {
  @override
  _i15.Stream<List<_i9.RecurringTemplate>> watchRecurringTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#watchRecurringTemplates, []),
            returnValue: _i15.Stream<List<_i9.RecurringTemplate>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i9.RecurringTemplate>>.empty(),
          )
          as _i15.Stream<List<_i9.RecurringTemplate>>);

  @override
  _i15.Stream<List<_i9.DueRecurringTemplate>> watchDueRecurringTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#watchDueRecurringTemplates, []),
            returnValue: _i15.Stream<List<_i9.DueRecurringTemplate>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i9.DueRecurringTemplate>>.empty(),
          )
          as _i15.Stream<List<_i9.DueRecurringTemplate>>);

  @override
  _i15.Future<_i9.RecurringTemplate> createRecurringTemplate({
    required String? name,
    required _i17.TransactionDirection? direction,
    required String? financialAccountId,
    required String? categoryId,
    required int? amountMinor,
    required int? dayOfMonth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRecurringTemplate, [], {
              #name: name,
              #direction: direction,
              #financialAccountId: financialAccountId,
              #categoryId: categoryId,
              #amountMinor: amountMinor,
              #dayOfMonth: dayOfMonth,
            }),
            returnValue: _i15.Future<_i9.RecurringTemplate>.value(
              _FakeRecurringTemplate_7(
                this,
                Invocation.method(#createRecurringTemplate, [], {
                  #name: name,
                  #direction: direction,
                  #financialAccountId: financialAccountId,
                  #categoryId: categoryId,
                  #amountMinor: amountMinor,
                  #dayOfMonth: dayOfMonth,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<_i9.RecurringTemplate>.value(
              _FakeRecurringTemplate_7(
                this,
                Invocation.method(#createRecurringTemplate, [], {
                  #name: name,
                  #direction: direction,
                  #financialAccountId: financialAccountId,
                  #categoryId: categoryId,
                  #amountMinor: amountMinor,
                  #dayOfMonth: dayOfMonth,
                }),
              ),
            ),
          )
          as _i15.Future<_i9.RecurringTemplate>);

  @override
  _i15.Future<void> updateRecurringTemplate({
    required String? id,
    required String? name,
    required _i17.TransactionDirection? direction,
    required String? financialAccountId,
    required String? categoryId,
    required int? amountMinor,
    required int? dayOfMonth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecurringTemplate, [], {
              #id: id,
              #name: name,
              #direction: direction,
              #financialAccountId: financialAccountId,
              #categoryId: categoryId,
              #amountMinor: amountMinor,
              #dayOfMonth: dayOfMonth,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> deleteRecurringTemplate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurringTemplate, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String> recordDueTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#recordDueTemplate, [templateId]),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordDueTemplate, [templateId]),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#recordDueTemplate, [templateId]),
              ),
            ),
          )
          as _i15.Future<String>);
}

/// A class which mocks [LedgerBackupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLedgerBackupRepository extends _i1.Mock
    implements _i35.LedgerBackupRepository {
  @override
  _i15.Future<String> exportLedgerBackup({
    required String? passphrase,
    _i36.File? databaseFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportLedgerBackup, [], {
              #passphrase: passphrase,
              #databaseFile: databaseFile,
            }),
            returnValue: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportLedgerBackup, [], {
                  #passphrase: passphrase,
                  #databaseFile: databaseFile,
                }),
              ),
            ),
            returnValueForMissingStub: _i15.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#exportLedgerBackup, [], {
                  #passphrase: passphrase,
                  #databaseFile: databaseFile,
                }),
              ),
            ),
          )
          as _i15.Future<String>);

  @override
  _i15.Future<void> restoreLedgerBackup({
    required String? fileContents,
    required String? passphrase,
    _i36.File? targetFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreLedgerBackup, [], {
              #fileContents: fileContents,
              #passphrase: passphrase,
              #targetFile: targetFile,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [ExchangeRateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateService extends _i1.Mock
    implements _i37.ExchangeRateService {
  @override
  _i15.Future<double?> fetchRate({
    required String? from,
    required String? to,
    required _i38.ExchangeRateProvider? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRate, [], {
              #from: from,
              #to: to,
              #provider: provider,
            }),
            returnValue: _i15.Future<double?>.value(),
            returnValueForMissingStub: _i15.Future<double?>.value(),
          )
          as _i15.Future<double?>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i39.SettingsRepository {
  @override
  _i15.Future<bool> isReferenceRateLookupEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isReferenceRateLookupEnabled, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setReferenceRateLookupEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setReferenceRateLookupEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i38.ExchangeRateProvider> selectedProvider() =>
      (super.noSuchMethod(
            Invocation.method(#selectedProvider, []),
            returnValue: _i15.Future<_i38.ExchangeRateProvider>.value(
              _i38.ExchangeRateProvider.frankfurter,
            ),
            returnValueForMissingStub:
                _i15.Future<_i38.ExchangeRateProvider>.value(
                  _i38.ExchangeRateProvider.frankfurter,
                ),
          )
          as _i15.Future<_i38.ExchangeRateProvider>);

  @override
  _i15.Future<void> setSelectedProvider(_i38.ExchangeRateProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedProvider, [provider]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> isAppLockEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isAppLockEnabled, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setAppLockEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAppLockEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<int> appLockTimeoutMinutes() =>
      (super.noSuchMethod(
            Invocation.method(#appLockTimeoutMinutes, []),
            returnValue: _i15.Future<int>.value(0),
            returnValueForMissingStub: _i15.Future<int>.value(0),
          )
          as _i15.Future<int>);

  @override
  _i15.Future<void> setAppLockTimeoutMinutes(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setAppLockTimeoutMinutes, [minutes]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> isAppLockBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isAppLockBiometricEnabled, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setAppLockBiometricEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAppLockBiometricEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> isAppSwitcherSnapshotHidingEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isAppSwitcherSnapshotHidingEnabled, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setAppSwitcherSnapshotHidingEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAppSwitcherSnapshotHidingEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> isFirstWeekSetupCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isFirstWeekSetupCompleted, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setFirstWeekSetupCompleted(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFirstWeekSetupCompleted, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> isMarketPriceFetchEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isMarketPriceFetchEnabled, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setMarketPriceFetchEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setMarketPriceFetchEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i40.QuoteProvider> selectedQuoteProvider() =>
      (super.noSuchMethod(
            Invocation.method(#selectedQuoteProvider, []),
            returnValue: _i15.Future<_i40.QuoteProvider>.value(
              _i40.QuoteProvider.stooq,
            ),
            returnValueForMissingStub: _i15.Future<_i40.QuoteProvider>.value(
              _i40.QuoteProvider.stooq,
            ),
          )
          as _i15.Future<_i40.QuoteProvider>);

  @override
  _i15.Future<void> setSelectedQuoteProvider(_i40.QuoteProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedQuoteProvider, [provider]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i41.ResearchTool> selectedResearchTool() =>
      (super.noSuchMethod(
            Invocation.method(#selectedResearchTool, []),
            returnValue: _i15.Future<_i41.ResearchTool>.value(
              _i41.ResearchTool.chatGpt,
            ),
            returnValueForMissingStub: _i15.Future<_i41.ResearchTool>.value(
              _i41.ResearchTool.chatGpt,
            ),
          )
          as _i15.Future<_i41.ResearchTool>);

  @override
  _i15.Future<void> setSelectedResearchTool(_i41.ResearchTool? tool) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedResearchTool, [tool]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<String?> preferredLocaleTag() =>
      (super.noSuchMethod(
            Invocation.method(#preferredLocaleTag, []),
            returnValue: _i15.Future<String?>.value(),
            returnValueForMissingStub: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<void> setPreferredLocaleTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredLocaleTag, [tag]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [StatementImportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatementImportRepository extends _i1.Mock
    implements _i42.StatementImportRepository {
  @override
  _i10.StatementParseResult parseOfxFile(List<int>? bytes) =>
      (super.noSuchMethod(
            Invocation.method(#parseOfxFile, [bytes]),
            returnValue: _FakeStatementParseResult_8(
              this,
              Invocation.method(#parseOfxFile, [bytes]),
            ),
            returnValueForMissingStub: _FakeStatementParseResult_8(
              this,
              Invocation.method(#parseOfxFile, [bytes]),
            ),
          )
          as _i10.StatementParseResult);

  @override
  _i10.StatementParseResult parseCsvFile(
    List<int>? bytes,
    _i43.CsvColumnMapping? mapping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseCsvFile, [bytes, mapping]),
            returnValue: _FakeStatementParseResult_8(
              this,
              Invocation.method(#parseCsvFile, [bytes, mapping]),
            ),
            returnValueForMissingStub: _FakeStatementParseResult_8(
              this,
              Invocation.method(#parseCsvFile, [bytes, mapping]),
            ),
          )
          as _i10.StatementParseResult);

  @override
  _i15.Future<String?> groupCurrencyFor(String? financialAccountId) =>
      (super.noSuchMethod(
            Invocation.method(#groupCurrencyFor, [financialAccountId]),
            returnValue: _i15.Future<String?>.value(),
            returnValueForMissingStub: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<Set<int>> findDuplicateIndexes({
    required String? financialAccountId,
    required List<_i10.ParsedStatementTransaction>? transactions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findDuplicateIndexes, [], {
              #financialAccountId: financialAccountId,
              #transactions: transactions,
            }),
            returnValue: _i15.Future<Set<int>>.value(<int>{}),
            returnValueForMissingStub: _i15.Future<Set<int>>.value(<int>{}),
          )
          as _i15.Future<Set<int>>);

  @override
  _i15.Future<_i11.StatementImportPreview> buildPreviewRows({
    required String? financialAccountId,
    required List<_i10.ParsedStatementTransaction>? transactions,
    required List<_i44.CategoryRule>? rules,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildPreviewRows, [], {
              #financialAccountId: financialAccountId,
              #transactions: transactions,
              #rules: rules,
            }),
            returnValue: _i15.Future<_i11.StatementImportPreview>.value(
              _FakeStatementImportPreview_9(
                this,
                Invocation.method(#buildPreviewRows, [], {
                  #financialAccountId: financialAccountId,
                  #transactions: transactions,
                  #rules: rules,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i11.StatementImportPreview>.value(
                  _FakeStatementImportPreview_9(
                    this,
                    Invocation.method(#buildPreviewRows, [], {
                      #financialAccountId: financialAccountId,
                      #transactions: transactions,
                      #rules: rules,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i11.StatementImportPreview>);

  @override
  _i15.Future<String?> suggestCategoryFor({
    required String? financialAccountId,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#suggestCategoryFor, [], {
              #financialAccountId: financialAccountId,
              #description: description,
            }),
            returnValue: _i15.Future<String?>.value(),
            returnValueForMissingStub: _i15.Future<String?>.value(),
          )
          as _i15.Future<String?>);

  @override
  _i15.Future<_i12.StatementImportBatchResult> postAcceptedRows({
    required String? financialAccountId,
    required List<_i12.StatementAcceptedRow>? rows,
    required _i45.ImportSource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postAcceptedRows, [], {
              #financialAccountId: financialAccountId,
              #rows: rows,
              #source: source,
            }),
            returnValue: _i15.Future<_i12.StatementImportBatchResult>.value(
              _FakeStatementImportBatchResult_10(
                this,
                Invocation.method(#postAcceptedRows, [], {
                  #financialAccountId: financialAccountId,
                  #rows: rows,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i15.Future<_i12.StatementImportBatchResult>.value(
                  _FakeStatementImportBatchResult_10(
                    this,
                    Invocation.method(#postAcceptedRows, [], {
                      #financialAccountId: financialAccountId,
                      #rows: rows,
                      #source: source,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i12.StatementImportBatchResult>);

  @override
  _i15.Future<void> saveProfile({
    required String? name,
    required _i43.CsvColumnMapping? mapping,
    required List<String>? headerRow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [], {
              #name: name,
              #mapping: mapping,
              #headerRow: headerRow,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<_i46.CsvImportProfile?> findProfileForHeaderRow(
    List<String>? headerRow,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findProfileForHeaderRow, [headerRow]),
            returnValue: _i15.Future<_i46.CsvImportProfile?>.value(),
            returnValueForMissingStub:
                _i15.Future<_i46.CsvImportProfile?>.value(),
          )
          as _i15.Future<_i46.CsvImportProfile?>);

  @override
  _i15.Stream<List<_i46.CsvImportProfile>> watchProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#watchProfiles, []),
            returnValue: _i15.Stream<List<_i46.CsvImportProfile>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i46.CsvImportProfile>>.empty(),
          )
          as _i15.Stream<List<_i46.CsvImportProfile>>);

  @override
  _i15.Future<void> renameProfile({
    required String? id,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameProfile, [], {#id: id, #newName: newName}),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> deleteProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> saveCategoryRule({
    required String? keyword,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCategoryRule, [], {
              #keyword: keyword,
              #categoryId: categoryId,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Stream<List<_i44.CategoryRule>> watchCategoryRules() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoryRules, []),
            returnValue: _i15.Stream<List<_i44.CategoryRule>>.empty(),
            returnValueForMissingStub:
                _i15.Stream<List<_i44.CategoryRule>>.empty(),
          )
          as _i15.Stream<List<_i44.CategoryRule>>);

  @override
  _i15.Future<void> updateCategoryRule({
    required String? id,
    required String? keyword,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategoryRule, [], {
              #id: id,
              #keyword: keyword,
              #categoryId: categoryId,
            }),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> deleteCategoryRule(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategoryRule, [id]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [AppLockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLockService extends _i1.Mock implements _i47.AppLockService {
  @override
  _i15.Future<bool> hasPinSet() =>
      (super.noSuchMethod(
            Invocation.method(#hasPinSet, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> setPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setPin, [pin]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<bool> verifyPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<void> clearPin() =>
      (super.noSuchMethod(
            Invocation.method(#clearPin, []),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);
}

/// A class which mocks [BiometricAuthenticator].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricAuthenticator extends _i1.Mock
    implements _i48.BiometricAuthenticator {
  @override
  _i15.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> authenticate({required String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {#reason: reason}),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);
}

/// A class which mocks [AppLockController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLockController extends _i1.Mock implements _i49.AppLockController {
  @override
  _i13.AppLockPolicy get policy =>
      (super.noSuchMethod(
            Invocation.getter(#policy),
            returnValue: _FakeAppLockPolicy_11(
              this,
              Invocation.getter(#policy),
            ),
            returnValueForMissingStub: _FakeAppLockPolicy_11(
              this,
              Invocation.getter(#policy),
            ),
          )
          as _i13.AppLockPolicy);

  @override
  bool get isUnlocked =>
      (super.noSuchMethod(
            Invocation.getter(#isUnlocked),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isBackgrounded =>
      (super.noSuchMethod(
            Invocation.getter(#isBackgrounded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSnapshotHidingEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isSnapshotHidingEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i15.Future<void> setSnapshotHidingEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSnapshotHidingEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setLockEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLockEnabled, [value]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  _i15.Future<void> setTimeoutMinutes(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setTimeoutMinutes, [minutes]),
            returnValue: _i15.Future<void>.value(),
            returnValueForMissingStub: _i15.Future<void>.value(),
          )
          as _i15.Future<void>);

  @override
  void markUnlocked() => super.noSuchMethod(
    Invocation.method(#markUnlocked, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i50.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i50.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i50.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  bool handleStartBackGesture(_i51.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i51.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  _i15.Future<bool> didPushRouteInformation(
    _i52.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i15.Future<bool>.value(false),
            returnValueForMissingStub: _i15.Future<bool>.value(false),
          )
          as _i15.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i50.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i50.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Future<_i50.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i15.Future<_i50.AppExitResponse>.value(
              _i50.AppExitResponse.exit,
            ),
            returnValueForMissingStub: _i15.Future<_i50.AppExitResponse>.value(
              _i50.AppExitResponse.exit,
            ),
          )
          as _i15.Future<_i50.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
