#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#endif
import Foundation
import Security

/// The device's TLS identity in the Keychain (design D4).
///
/// The RSA-2048 private key is generated by `SecKeyCreateRandomKey` as a
/// permanent, non-synchronizable, non-extractable item, accessible only when
/// the device is unlocked and never migrating to another device.
///
/// On macOS every item lives in the data-protection keychain (the iOS-style
/// one), not the legacy file-based login keychain. The legacy keychain gates
/// each key by the signing app's code signature and shows an "allow access"
/// dialog when it changes; the TLS handshake then blocked on that dialog
/// while signing. The data-protection keychain grants access by the app's
/// application identifier instead, which App Store builds and team-signed
/// debug builds both carry. Dart receives only the public key and signatures;
/// the certificate it assembles is stored next to the key so the Security
/// framework can pair them into a `SecIdentity` for the Network framework.
final class KeychainIdentityHandler {
    private static let tagPrefix = "com.smara.account.tls."

    func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let args = call.arguments as? [String: Any] ?? [:]
        do {
            switch call.method {
            case "createRsaKey":
                let label = try PluginArgs.string(args, "label")
                let bits = (args["bits"] as? Int) ?? 2048
                result(PluginArgs.typed(try createRsaKey(label: label, bits: bits)))
            case "publicKey":
                let label = try PluginArgs.string(args, "label")
                if let key = privateKey(label: label) {
                    result(PluginArgs.typed(try publicKeyDer(of: key)))
                } else {
                    result(nil)
                }
            case "signPkcs1Sha256":
                let label = try PluginArgs.string(args, "label")
                result(PluginArgs.typed(try sign(label: label, data: try PluginArgs.bytes(args, "data"))))
            case "storeCertificate":
                let label = try PluginArgs.string(args, "label")
                try storeCertificate(label: label, der: try PluginArgs.bytes(args, "der"))
                result(nil)
            case "hasIdentity":
                let label = try PluginArgs.string(args, "label")
                result((try? identity(label: label)) != nil)
            case "deleteIdentity":
                let label = try PluginArgs.string(args, "label")
                deleteIdentity(label: label)
                result(nil)
            default:
                result(FlutterMethodNotImplemented)
            }
        } catch {
            result(PluginArgs.flutterError(error))
        }
    }

    private static func tag(_ label: String) -> Data {
        Data((tagPrefix + label).utf8)
    }

    /// Adds the keychain selection to a query or attribute dictionary: the
    /// data-protection keychain on macOS (it is the only one on iOS).
    private static func scoped(_ query: [CFString: Any]) -> [CFString: Any] {
        #if os(macOS)
        var q = query
        q[kSecUseDataProtectionKeychain] = true
        return q
        #else
        return query
        #endif
    }

    func createRsaKey(label: String, bits: Int) throws -> Data {
        deleteIdentity(label: label)
        let privateAttrs: [CFString: Any] = [
            kSecAttrIsPermanent: true,
            kSecAttrApplicationTag: Self.tag(label),
            kSecAttrLabel: label,
            kSecAttrAccessible: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            kSecAttrIsExtractable: false,
        ]
        let attrs: [CFString: Any] = Self.scoped([
            kSecAttrKeyType: kSecAttrKeyTypeRSA,
            kSecAttrKeySizeInBits: bits,
            kSecAttrLabel: label,
            kSecPrivateKeyAttrs: privateAttrs,
        ])
        var error: Unmanaged<CFError>?
        guard let key = SecKeyCreateRandomKey(attrs as CFDictionary, &error) else {
            throw PluginError(
                code: "key_generation_failed",
                message: "SecKeyCreateRandomKey: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return try publicKeyDer(of: key)
    }

    func privateKey(label: String) -> SecKey? {
        let query: [CFString: Any] = Self.scoped([
            kSecClass: kSecClassKey,
            kSecAttrApplicationTag: Self.tag(label),
            kSecAttrKeyType: kSecAttrKeyTypeRSA,
            kSecReturnRef: true,
            kSecMatchLimit: kSecMatchLimitOne,
        ])
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let ref = item else { return nil }
        return (ref as! SecKey)
    }

    /// PKCS#1 `RSAPublicKey` DER, which is what `SecKeyCopyExternalRepresentation`
    /// returns for RSA keys.
    func publicKeyDer(of privateKey: SecKey) throws -> Data {
        guard let publicKey = SecKeyCopyPublicKey(privateKey) else {
            throw PluginError(code: "public_key_failed", message: "SecKeyCopyPublicKey returned nil.")
        }
        var error: Unmanaged<CFError>?
        guard let der = SecKeyCopyExternalRepresentation(publicKey, &error) as Data? else {
            throw PluginError(
                code: "public_key_failed",
                message: "SecKeyCopyExternalRepresentation: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return der
    }

    func sign(label: String, data: Data) throws -> Data {
        guard let key = privateKey(label: label) else {
            throw PluginError(code: "no_identity", message: "No private key under '\(label)'.")
        }
        var error: Unmanaged<CFError>?
        guard
            let signature = SecKeyCreateSignature(
                key, .rsaSignatureMessagePKCS1v15SHA256, data as CFData, &error) as Data?
        else {
            throw PluginError(
                code: "sign_failed",
                message: "SecKeyCreateSignature: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return signature
    }

    func storeCertificate(label: String, der: Data) throws {
        guard let certificate = SecCertificateCreateWithData(nil, der as CFData) else {
            throw PluginError(code: "bad_certificate", message: "Certificate DER did not parse.")
        }
        SecItemDelete(Self.scoped([kSecClass: kSecClassCertificate, kSecAttrLabel: label]) as CFDictionary)
        let attrs: [CFString: Any] = Self.scoped([
            kSecClass: kSecClassCertificate,
            kSecValueRef: certificate,
            kSecAttrLabel: label,
            kSecAttrAccessible: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
        ])
        let status = SecItemAdd(attrs as CFDictionary, nil)
        guard status == errSecSuccess || status == errSecDuplicateItem else {
            throw PluginError(code: "store_certificate_failed", message: "SecItemAdd status \(status).")
        }
    }

    /// The `SecIdentity` pairing the certificate and private key under
    /// [label]; used as the local TLS identity.
    func identity(label: String) throws -> SecIdentity {
        // The data-protection keychain pairs a certificate with its private
        // key into an identity on both iOS and macOS.
        let query: [CFString: Any] = Self.scoped([
            kSecClass: kSecClassIdentity,
            kSecAttrLabel: label,
            kSecReturnRef: true,
            kSecMatchLimit: kSecMatchLimitOne,
        ])
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let ref = item {
            return (ref as! SecIdentity)
        }
        throw PluginError(code: "no_identity", message: "No TLS identity under '\(label)' (status \(status)).")
    }

    func deleteIdentity(label: String) {
        SecItemDelete(Self.scoped([kSecClass: kSecClassCertificate, kSecAttrLabel: label]) as CFDictionary)
        SecItemDelete(
            Self.scoped([
                kSecClass: kSecClassKey,
                kSecAttrApplicationTag: Self.tag(label),
            ]) as CFDictionary)
    }
}
