#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#endif
import Foundation
import Security

/// The device's TLS identity in the Keychain (design D4).
///
/// The RSA-2048 private key is generated by `SecKeyCreateRandomKey` as a
/// permanent, non-synchronizable item. On iOS it is accessible only when the
/// device is unlocked and never migrates to another device; on macOS it is
/// marked non-extractable. Dart receives only the public key and signatures;
/// the certificate it assembles is stored next to the key so the Security
/// framework can pair them into a `SecIdentity` for the Network framework.
final class KeychainIdentityHandler {
    private static let tagPrefix = "com.smara.account.tls."

    func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let args = call.arguments as? [String: Any] ?? [:]
        do {
            switch call.method {
            case "createRsaKey":
                let label = try PluginArgs.string(args, "label")
                let bits = (args["bits"] as? Int) ?? 2048
                result(PluginArgs.typed(try createRsaKey(label: label, bits: bits)))
            case "publicKey":
                let label = try PluginArgs.string(args, "label")
                if let key = privateKey(label: label) {
                    result(PluginArgs.typed(try publicKeyDer(of: key)))
                } else {
                    result(nil)
                }
            case "signPkcs1Sha256":
                let label = try PluginArgs.string(args, "label")
                result(PluginArgs.typed(try sign(label: label, data: try PluginArgs.bytes(args, "data"))))
            case "storeCertificate":
                let label = try PluginArgs.string(args, "label")
                try storeCertificate(label: label, der: try PluginArgs.bytes(args, "der"))
                result(nil)
            case "hasIdentity":
                let label = try PluginArgs.string(args, "label")
                result((try? identity(label: label)) != nil)
            case "deleteIdentity":
                let label = try PluginArgs.string(args, "label")
                deleteIdentity(label: label)
                result(nil)
            default:
                result(FlutterMethodNotImplemented)
            }
        } catch {
            result(PluginArgs.flutterError(error))
        }
    }

    private static func tag(_ label: String) -> Data {
        Data((tagPrefix + label).utf8)
    }

    func createRsaKey(label: String, bits: Int) throws -> Data {
        deleteIdentity(label: label)
        var privateAttrs: [CFString: Any] = [
            kSecAttrIsPermanent: true,
            kSecAttrApplicationTag: Self.tag(label),
            kSecAttrLabel: label,
        ]
        #if os(iOS)
        privateAttrs[kSecAttrAccessible] = kSecAttrAccessibleWhenUnlockedThisDeviceOnly
        #else
        privateAttrs[kSecAttrIsExtractable] = false
        #endif
        let attrs: [CFString: Any] = [
            kSecAttrKeyType: kSecAttrKeyTypeRSA,
            kSecAttrKeySizeInBits: bits,
            kSecAttrLabel: label,
            kSecPrivateKeyAttrs: privateAttrs,
        ]
        var error: Unmanaged<CFError>?
        guard let key = SecKeyCreateRandomKey(attrs as CFDictionary, &error) else {
            throw PluginError(
                code: "key_generation_failed",
                message: "SecKeyCreateRandomKey: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return try publicKeyDer(of: key)
    }

    func privateKey(label: String) -> SecKey? {
        let query: [CFString: Any] = [
            kSecClass: kSecClassKey,
            kSecAttrApplicationTag: Self.tag(label),
            kSecAttrKeyType: kSecAttrKeyTypeRSA,
            kSecReturnRef: true,
            kSecMatchLimit: kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let ref = item else { return nil }
        return (ref as! SecKey)
    }

    /// PKCS#1 `RSAPublicKey` DER, which is what `SecKeyCopyExternalRepresentation`
    /// returns for RSA keys.
    func publicKeyDer(of privateKey: SecKey) throws -> Data {
        guard let publicKey = SecKeyCopyPublicKey(privateKey) else {
            throw PluginError(code: "public_key_failed", message: "SecKeyCopyPublicKey returned nil.")
        }
        var error: Unmanaged<CFError>?
        guard let der = SecKeyCopyExternalRepresentation(publicKey, &error) as Data? else {
            throw PluginError(
                code: "public_key_failed",
                message: "SecKeyCopyExternalRepresentation: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return der
    }

    func sign(label: String, data: Data) throws -> Data {
        guard let key = privateKey(label: label) else {
            throw PluginError(code: "no_identity", message: "No private key under '\(label)'.")
        }
        var error: Unmanaged<CFError>?
        guard
            let signature = SecKeyCreateSignature(
                key, .rsaSignatureMessagePKCS1v15SHA256, data as CFData, &error) as Data?
        else {
            throw PluginError(
                code: "sign_failed",
                message: "SecKeyCreateSignature: \(error?.takeRetainedValue().localizedDescription ?? "unknown")")
        }
        return signature
    }

    func storeCertificate(label: String, der: Data) throws {
        guard let certificate = SecCertificateCreateWithData(nil, der as CFData) else {
            throw PluginError(code: "bad_certificate", message: "Certificate DER did not parse.")
        }
        SecItemDelete([kSecClass: kSecClassCertificate, kSecAttrLabel: label] as CFDictionary)
        let attrs: [CFString: Any] = [
            kSecClass: kSecClassCertificate,
            kSecValueRef: certificate,
            kSecAttrLabel: label,
        ]
        let status = SecItemAdd(attrs as CFDictionary, nil)
        guard status == errSecSuccess || status == errSecDuplicateItem else {
            throw PluginError(code: "store_certificate_failed", message: "SecItemAdd status \(status).")
        }
    }

    /// The `SecIdentity` pairing the certificate and private key under
    /// [label]; used as the local TLS identity.
    func identity(label: String) throws -> SecIdentity {
        let query: [CFString: Any] = [
            kSecClass: kSecClassIdentity,
            kSecAttrLabel: label,
            kSecReturnRef: true,
            kSecMatchLimit: kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let ref = item {
            return (ref as! SecIdentity)
        }
        #if os(macOS)
        // The file-based macOS Keychain pairs lazily; build the identity from
        // the stored certificate when the query finds nothing.
        let certQuery: [CFString: Any] = [
            kSecClass: kSecClassCertificate,
            kSecAttrLabel: label,
            kSecReturnRef: true,
            kSecMatchLimit: kSecMatchLimitOne,
        ]
        var certItem: CFTypeRef?
        if SecItemCopyMatching(certQuery as CFDictionary, &certItem) == errSecSuccess, let certRef = certItem {
            var identityRef: SecIdentity?
            let created = SecIdentityCreateWithCertificate(nil, certRef as! SecCertificate, &identityRef)
            if created == errSecSuccess, let found = identityRef {
                return found
            }
        }
        #endif
        throw PluginError(code: "no_identity", message: "No TLS identity under '\(label)' (status \(status)).")
    }

    func deleteIdentity(label: String) {
        SecItemDelete([kSecClass: kSecClassCertificate, kSecAttrLabel: label] as CFDictionary)
        SecItemDelete(
            [
                kSecClass: kSecClassKey,
                kSecAttrApplicationTag: Self.tag(label),
            ] as CFDictionary)
    }
}
