/// Stable, language-agnostic codes for user-visible failures.
/// UI maps these through [localizeError]; repositories must not emit
/// display English as the only signal.
enum AppErrorCode {
  generic,
  signingIdentityMismatch,
  invalidLedgerBackup,
  invalidLedgerBackupNoIdentity,
  invalidLedgerBackupUnverified,
  invalidLedgerBackupUnreadable,
  foreignBackupIdentity,
  accountNotFinancial,
  accountArchived,
  accountNotArchived,
  accountNoPositiveBalanceToCloseOut,
  accountHasNoGroup,
  groupHasNoCurrency,
  groupNotFound,
  investmentAccountsMustBeAssets,
  creditCardsMustBeLiabilities,
  openingBalanceMustBePositive,
  accountTypeDoesNotMatchGroup,
  lastActiveAccount,
  currencyRequiredToCreateGroup,
  systemGroupCannotBeArchived,
  groupAlreadyArchived,
  cannotArchiveGroupWithAccounts,
  systemGroupNeverArchived,
  accountGroupsCannotBeDeleted,
  cannotReassignDifferentCurrency,
  cannotChangeGroupCurrencyWithAccounts,
  amountMustBePositive,
  accountCurrencyAmountMustBePositive,
  accountCurrencyAmountNotForSameCurrency,
  splitNeedsTwoLines,
  splitLineMustBePositive,
  splitLinesMustSumToTotal,
  transferAmountMustBePositive,
  transferAccountsMustDiffer,
  closeoutRequiresDestinationAmount,
  destinationAmountNotForSameCurrency,
  destinationAmountMustBePositive,
  investmentCashExceeded,
  cannotReverseUnsettledProvisional,
  alreadyReversed,
  notActiveExpenseCategory,
  notActiveIncomeCategory,
  settledAmountMustNotBeNegative,
  pendingTransferNotFound,
  pendingTransferAlreadySettled,
  settledToMustBeSourceOrDestination,
  feeCategoryOnlyWhenReturningToSource,
  settledAmountMustBePositiveForDelivery,
  settledAmountExceedsProvisional,
  instrumentNotFound,
  incomeRequiredForNonCash,
  insufficientCash,
  buyQuantityAndPriceMustBePositive,
  sellQuantityAndPriceMustBePositive,
  instrumentArchived,
  nonCashCannotIncludeBrokerage,
  brokerageRequiresExpenseCategory,
  sellProceedsMustCoverBrokerage,
  lockedUntil,
  insufficientQuantity,
  incomeRequiredForGain,
  expenseRequiredForLoss,
  brokerageFailedAfterBuy,
  brokerageFailedAfterSell,
  dividendMustBePositive,
  notInvestmentAccount,
  noInventoryCompanion,
  investmentReversalBlocked,
  monthlyLimitMustBePositive,
  templateAmountMustBePositive,
  ofxUnrecognized,
  csvEmpty,
  csvUnreadable,
  csvNoRows,
  backupCreateFailed,
  backupRestoreFailed,
  validationAmountAccountCategoryRequired,
  validationAmountAccountRequired,
  validationSplitLineIncomplete,
  validationSplitSumMismatch,
  validationFromToAmountRequired,
  validationAmountArrivedRequired,
  validationChooseReceivingAccount,
  validationAccountCategoryRequired,
  validationFixFailed,
  validationNameRequired,
  validationStillLoading,
  validationSaveAccountNameFailed,
  validationWrongPin,
  validationCategoryMustBeIncomeOrExpense,
  validationOnlyExpenseHasMonthlyLimit,
  validationInvalidTemplate,
  validationWrongKeystorePassphrase,
  validationInvalidKeystoreFile,
  validationRestorePhraseFailed,
  validationGenerateKeyFailed,
  validationSaveCurrencyFailed,
  validationMigrationFailed,
  validationChooseBackupFile,
  validationPassphraseRequired,
  validationPinsDoNotMatch,
  validationFeePositiveWithCategory,
  validationFeeMustBeLessThanAmount,
  validationTransferSavedFeeFailed,
  validationEnterValidAmount,
  validationConfirmWordMismatch,
}

/// Structured failure the UI can localize without parsing English prose.
class AppFailure implements Exception {
  const AppFailure(this.code, {this.params = const {}, this.debugMessage});

  final AppErrorCode code;
  final Map<String, String> params;
  final String? debugMessage;

  @override
  String toString() => debugMessage ?? code.name;
}
